name: format

on:
  workflow_dispatch:
  push:
    paths:
      - package.json

permissions:
  contents: write
  packages: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Format *.channels.xml files
        run: npm run channels:format

      - name: Detect changes
        id: files
        run: |
          CHANNELS_ANY_CHANGED=false
          CHANNELS_ALL_CHANGED_FILES=$(git diff --diff-filter=ACMRT --name-only -- 'sites/**/*.channels.xml' | tr '\n' ' ')
          if [ -n "${CHANNELS_ALL_CHANGED_FILES}" ]; then
            CHANNELS_ANY_CHANGED=true
          fi

          LOCKFILES_ANY_CHANGED=false
          LOCKFILES_CHANGED_FILES=$(git diff --diff-filter=ACMRT --name-only -- package.json package-lock.json | tr '\n' ' ')
          if [ -n "${LOCKFILES_CHANGED_FILES}" ]; then
            LOCKFILES_ANY_CHANGED=true
          fi

          ANY_CHANGED=false
          if [ "$CHANNELS_ANY_CHANGED" = "true" ] || [ "$LOCKFILES_ANY_CHANGED" = "true" ]; then
            ANY_CHANGED=true
          fi

          echo "channels_all_changed_files=$CHANNELS_ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "channels_any_changed=$CHANNELS_ANY_CHANGED" >> "$GITHUB_OUTPUT"
          echo "lockfiles_changed_files=$LOCKFILES_CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "lockfiles_any_changed=$LOCKFILES_ANY_CHANGED" >> "$GITHUB_OUTPUT"
          echo "any_changed=$ANY_CHANGED" >> "$GITHUB_OUTPUT"

      - name: Check changed *.channels.xml files
        if: steps.files.outputs.channels_any_changed == 'true'
        run: |
          npm run channels:lint -- ${{ steps.files.outputs.channels_all_changed_files }}
          npm run channels:validate -- ${{ steps.files.outputs.channels_all_changed_files }}

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        if: steps.files.outputs.any_changed == 'true'
        run: |
          git add sites package.json package-lock.json
          git status
          git commit -m "[Bot] Format channels and update lockfile" -m "Committed by github-actions via format workflow." --no-verify

      - name: Push all changes to the repository
        if: ${{ github.ref == 'refs/heads/master' && steps.files.outputs.any_changed == 'true' }}
        run: git push
