name: Generar guias EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Actualizar canales tvpassport.com
        run: |
          mkdir -p sites/tvpassport.com
          echo "Actualizando canales tvpassport.com..."
          npm run channels:parse --- --config=./sites/tvpassport.com/tvpassport.com.config.js --output=./sites/tvpassport.com/tvpassport.com.channels.xml

      - name: Generar guias mi.tv
        run: |
          mkdir -p guides/mi.tv

          for code in ar br cl co sv gt hn mx py pe
          do
            echo "Generando mi.tv $code..."
            npm run grab --- --channels=sites/mi.tv/mi.tv_${code}.channels.xml --output=guides/mi.tv/${code}.xml
          done

      - name: Generar guia tvinsider.com
        run: |
          mkdir -p guides/tvinsider.com
          echo "Generando tvinsider.com..."
          npm run grab --- --site=tvinsider.com --output=guides/tvinsider.com/guide.xml

      - name: Generar guia movistarplus.es
        run: |
          mkdir -p guides/movistarplus.es
          echo "Generando movistarplus.es..."
          npm run grab --- --site=movistarplus.es --output=guides/movistarplus.es/guide.xml

      - name: Commit si hubo cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f guides/mi.tv/*.xml
          git add -f guides/tvinsider.com/*.xml
          git add -f guides/movistarplus.es/*.xml
          git add -f sites/tvpassport.com/*.xml
          git diff --cached --quiet || git commit -m "Actualizar guias EPG"
          git push
